---
- name: Linux timezone setup
  ansible.builtin.include_tasks: timezone.yml
  when: ansible_system == "Linux"

- name: FreeBSD timezone setup
  ansible.builtin.include_tasks: freebsd.yml
  when: ansible_system == "FreeBSD"
