---
- name: Linux timezone setup
  ansible.builtin.import_playbook: timezone.yml
  when: ansible_system == "Linux"

- name: FreeBSD timezone setup
  ansible.builtin.import_playbook: freebsd.yml
  when: ansible_system == "FreeBSD"
