---
- name: timezone | Include platform vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_facts.distribution }}.yml"
    - "../vars/{{ ansible_facts.os_family }}.yml"
  tags: ["timezone"]

- name: timezone | Install tzdata for Debian based distros
  ansible.builtin.apt:
    name: "{{ timezone_package }}"
    update_cache: true
    cache_valid_time: 86400
    state: present
  when: ansible_facts.os_family == 'Debian'
  tags: ["timezone"]
  become: true

- name: timezone | Install tzdata for RedHat based distros
  ansible.builtin.yum:
    name: "{{ timezone_package }}"
    state: present
  when: ansible_facts.os_family == 'RedHat'
  tags: ["timezone"]
  become: true

- name: timezone | Install tzdata for Archlinux based distros
  community.general.pacman:
    name: "{{ timezone_package }}"
    state: present
  when: ansible_facts.os_family == 'Archlinux' or ansible_facts.os_family == 'Arch Linux'
  tags: ["timezone"]
  become: true

- name: timezone | Set timezone config
  ansible.builtin.template:
    src: "timezone-{{ ansible_facts.os_family }}.j2"
    dest: "{{ timezone_file }}"
    mode: u=rw,g=r,o=r
  tags: ["timezone"]
  become: true

- name: timezone | Set link to localtime
  ansible.builtin.file:
    state: link
    src: "{{ zoneinfo_dir }}{{ timezone }}"
    dest: "{{ localtime_file }}"
    force: true
  tags: ["timezone"]
  become: true
