---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
verifier:
  name: ansible
platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    privileged: true
  - name: timezone-centos7
    image: centos:7
    privileged: true
  - name: timezone-centos6
    image: centos:6
    privileged: true
  - name: timezone-debian
    image: debian
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
